export const buttonThemes = {
  TRANSPARENT_LIGHT: 'TRANSPARENT_LIGHT',
  TRANSPARENT_DARK: 'TRANSPARENT_DARK',
  PRIMARY_LIGHT: 'PRIMARY_LIGHT',
  PRIMARY_DARK: 'PRIMARY_DARK',
  SECONDARY_LIGHT: 'SECONDARY_LIGHT',
  SECONDARY_DARK: 'SECONDARY_DARK',
  GRAY: 'GRAY',
};
